CREATE DATABASE bd3_malla_curricular_sistemas;
USE bd3_malla_curricular_sistemas;

CREATE TABLE MATERIA
(
SIGLA VARCHAR(6) NOT NULL PRIMARY KEY,
NOMBRE VARCHAR(60) NOT NULL,
SEMESTRE TINYINT NOT NULL
);

CREATE TABLE PREREQUISITO
(
SIGLAMAT VARCHAR(6) NOT NULL,
SIGLAPRE VARCHAR(6)  NOT NULL,
PRIMARY KEY (SIGLAMAT,SIGLAPRE),
foreign key (SIGLAMAT)references MATERIA(SIGLA)
	ON UPDATE CASCADE
    ON DELETE CASCADE,
foreign key (SIGLAPRE) REFERENCES MATERIA(SIGLA)
	ON UPDATE CASCADE
    ON DELETE CASCADE
);
-- MATERIAS:
-- 1er Semestre
INSERT INTO MATERIA VALUES ('MAT101','CALCULO I',1);
INSERT INTO MATERIA VALUES ('INF119','ESTRUCTURAS DISCRETAS',1);
INSERT INTO MATERIA VALUES ('INF110','INTRODUCCION A LA INFORMATICA',1);
INSERT INTO MATERIA VALUES ('FIS100','FISICA I',1);
INSERT INTO MATERIA VALUES ('LIN100','INGLES TECNICO I',1);
-- 2do Semestre
INSERT INTO MATERIA VALUES ('MAT102','CALCULO II',2);
INSERT INTO MATERIA VALUES ('MAT103','ALGEBRA LINEAL',2);
INSERT INTO MATERIA VALUES ('INF120','PROGRAMACION I',2);
INSERT INTO MATERIA VALUES ('FIS102','FISICA II',2);
INSERT INTO MATERIA VALUES ('LIN101','INGLES TECNICO II',2);
-- 3er Semestre
INSERT INTO MATERIA VALUES ('MAT207','ECUACIONES DIFERENCIALES',3);
INSERT INTO MATERIA VALUES ('INF210','PROGRAMACION II',3);
INSERT INTO MATERIA VALUES ('INF211','ARQUITECTURA DE COMPUTADORAS',3);
INSERT INTO MATERIA VALUES ('ADM100','ADMINISTRACION',3);
INSERT INTO MATERIA VALUES ('FIS200','FISICA III',3);
-- 4to Semestre
INSERT INTO MATERIA VALUES ('MAT202','PROBABILIDAD Y ESTADISTICA I',4);
INSERT INTO MATERIA VALUES ('MAT205','METODOS NUMERICOS',4);
INSERT INTO MATERIA VALUES ('INF220','ESTRUCTURA DE DATOS I',4);
INSERT INTO MATERIA VALUES ('INF221','PROGRAMACION ENSAMBLADOR',4);
INSERT INTO MATERIA VALUES ('ADM','CONTABILIDAD',4);
-- 5to Semestre
INSERT INTO MATERIA VALUES ('MAT302','PROBABILIDAD Y ESTADISTICA II',5);
INSERT INTO MATERIA VALUES ('INF310','ESTRUCTURA DE DATOS II',5);
INSERT INTO MATERIA VALUES ('ADM330','ORGANIZACION Y METODOS',5);
INSERT INTO MATERIA VALUES ('IN312','BASE DE DATOS I',5);
INSERT INTO MATERIA VALUES ('ECO300','ECONOMIA PARA LA GESTION',5);
-- 6to Semestre
INSERT INTO MATERIA VALUES ('MAT329','INVESTIGACION OPERATIVA I',6);
INSERT INTO MATERIA VALUES ('INF323','SISTEMAS OPERATIVOS I',6);
INSERT INTO MATERIA VALUES ('ADM320','FINANZAS PARA LA EMPRESA',6);
INSERT INTO MATERIA VALUES ('INF342','SISTEMAS DE INFORMACION I',6);
INSERT INTO MATERIA VALUES ('INF322','BASE DE DATOS II',6);
-- 7mo Semestre
INSERT INTO MATERIA VALUES ('MAT419','INVESTIGACION OPERATIVA II',7);
INSERT INTO MATERIA VALUES ('INF413','SISTEMAS OPERATIVOS II',7);
INSERT INTO MATERIA VALUES ('INF433','REDES I',7);
INSERT INTO MATERIA VALUES ('INF432','SISTEMAS PARA EL SOPORTE A LA TOMA DE DECISIONES',7);
INSERT INTO MATERIA VALUES ('INF412','SISTEMAS DE INFORMACION II',7);
-- 8vo Semestre
INSERT INTO MATERIA VALUES ('ECO449','PREPARACION Y EVALUACION DE PROYECTOS',8);
INSERT INTO MATERIA VALUES ('INF423','REDES II',8);
INSERT INTO MATERIA VALUES ('INF462','AUDITORIA INFORMATICA',8);
INSERT INTO MATERIA VALUES ('INF442','SISTEMAS DE INFORMACION GEOGRAFICA',8);
INSERT INTO MATERIA VALUES ('INF422','INGENIERIA DE SOFTWARE I',8);
-- 9no Semestre
INSERT INTO MATERIA VALUES ('INF511','TALLER DE GRADO I',9);
INSERT INTO MATERIA VALUES ('INF512','INGENIERIA DE SOFTWARE II',9);
INSERT INTO MATERIA VALUES ('INF513','TECNOLOGIA WEB',9);
INSERT INTO MATERIA VALUES ('INF552','ARQUITECTURA DE SOFTWARE',9);
-- 10mo Semestre
INSERT INTO MATERIA VALUES ('GRL001','MODALIDAD DE LICENCIATURA',10);



-- PREREQUISITOS:
INSERT INTO PREREQUISITO VALUES ('MAT102','MAT101'),
								('MAT103','INF119'),
								('INF120','INF110'),
								('FIS102','FIS100'),
								('LIN101','LIN100');

INSERT INTO PREREQUISITO VALUES ('MAT207','MAT102'),
								('INF210','MAT103'),
								('INF210','INF120'),
								('INF211','INF120'),
                                ('INF211','FIS102'),
                                ('FIS200','FIS102');
-- 4to Semestre                                
INSERT INTO PREREQUISITO VALUES ('MAT205','MAT207'),
								('MAT202','MAT102'),
								('INF220','INF210'),
                                ('INF220','MAT101'),
								('INF221','INF211'),
                                ('ADM200','ADM100');
                                
INSERT INTO PREREQUISITO VALUES ('MAT302','MAT202'),
								('INF310','INF220'),
								('INF312','ADM200'),
								('ECO300','ADM200'),
                                ('ADM330','ADM200');
                                
INSERT INTO PREREQUISITO VALUES ('MAT329','MAT302'),
								('INF323','INF310'),
								('ADM320','ADM330'),
								('INF342','INF312'),
                                ('INF322','INF312');
       
INSERT INTO PREREQUISITO VALUES ('MAT419','MAT329'),
								('INF433','INF323'),
								('INF413','INF323'),
								('INF432','INF342'),
                                ('INF412','INF342'),
                                ('INF432','INF322'),
                                ('INF412','INF322');
                                
                                
INSERT INTO PREREQUISITO VALUES ('ECO449','MAT419'),
								('INF423','INF433'),
								('INF462','ADM320'),
                                ('INF462','INF412'),
								('INF442','INF412'),
                                ('INF422','INF412');
						
INSERT INTO PREREQUISITO VALUES ('INF511','ECO449'),
								('INF511','INF423'),
								('INF511','INF462'),
                                ('INF511','INF442'),
								('INF511','INF422');
                                
                                
INSERT INTO PREREQUISITO VALUES ('INF512','ECO449'),
								('INF512','INF423'),
								('INF512','INF462'),
                                ('INF512','INF442'),
								('INF512','INF422');
                                
INSERT INTO PREREQUISITO VALUES ('INF512','ECO449'),
								('INF513','INF423'),
								('INF513','INF462'),
                                ('INF513','INF442'),
								('INF513','INF422');                                
                                
-- 10mo Semestre
INSERT INTO PREREQUISITO VALUES ('INF552','ECO449'),
								('INF552','INF423'),
								('INF552','INF462'),
                                ('INF552','INF442'),
								('INF552','INF422'); 
       
/**
 * MOSTRAR PARA QUE MATERIAS ES REQUISITO ARQUITECTURA DE COMPUTADORAS.
 */ 
-- FORMA 1
SELECT 
	MATERIAPRE.SIGLA, 
	MATERIAPRE.NOMBRE
FROM 
	MATERIA MATERIALLEVAR, 
	PREREQUISITO, 
	MATERIA MATERIAPRE
WHERE 
	MATERIALLEVAR.SIGLA = SIGLAMAT 
	AND 
	SIGLAPRE = MATERIAPRE.SIGLA 
	AND 
	MATERIALLEVAR.NOMBRE = 'ARQUITECTURA DE COMPUTADORAS';							
-- FORMA 2    
select 
	SIGLA, 
	NOMBRE 
from 
	materia
where
	SIGLA in 
	(
		select 
			SIGLAPRE 
		from 
			prerequisito
		where
			SIGLAMAT in 
			(
				select 
					SIGLA 
				from 
					materia
				where 
					NOMBRE = 'ARQUITECTURA DE COMPUTADORAS'
			)
	);
/**
 * MOSTRAR PARA QUE MATERIAS ES PROGRAMACION I.
 */
-- FORMA 1
SELECT 
	MATERIALLEVAR.SIGLA, 
	MATERIALLEVAR.NOMBRE
FROM 
	MATERIA MATERIAPRE, 
	PREREQUISITO, 
	MATERIA MATERIALLEVAR
WHERE 
	MATERIALLEVAR.SIGLA = SIGLAMAT 
	AND 
	SIGLAPRE = MATERIAPRE.SIGLA 
	AND 
	MATERIAPRE.NOMBRE = 'PROGRAMACION I';
-- FORMA 2    
select 
	SIGLA, 
	NOMBRE 
from 
	materia
where
	SIGLA in 
	(
		select 
			SIGLAMAT  
		from 
			PREREQUISITO
		where
			SIGLAPRE in 
			(
				SELECT 
					SIGLA 
				FROM
					MATERIA
				WHERE 
					NOMBRE = 'SISTEMAS DE INFORMACION II'
			)
	);

/**
 * MOSTRAR QUE MATERIAS NO TIENEN PREREQUISITO.
 */
select
	SIGLA,
	NOMBRE
from 
	materia
where 
	SIGLA not in 
	(
		select 
			SIGLAMAT
		from 
			prerequisito
	);

/**
 * MOSTRAR QUE MATERIAS TIENEN PREREQUISITO
 */
select
	SIGLA,
	NOMBRE
from 
	materia
where 
	SIGLA in 
	(
		select 
			SIGLAMAT
		from 
			prerequisito
	);